# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
    - run: npm install --global http-server
    - run: npm install
    - run: npm run coverage
    - run: ls -la
    - name: Archive test results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: test-result-junit
        path: junit.xml
    - name: Archive coverage results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: coverage-artifact
        path: coverage/*.xml

      

