# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v2
      with:
        node-version: '10'
        cache: 'npm'
    - run: npm update
    - run: sudo apt-get update
    - run: npm install --global http-server
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
